FROM debian:jessie

MAINTAINER Renzo Kottmann <renzo.kottmann@gmail.com>

RUN apt-get update && apt-get install -y \
    net-tools \
    postgresql-client-common \
    postgresql-client=9.4+165+deb8u1

# EXPOSE 5432

# CMD ["psql"]
